### ISSUE TITLE
동일한 날짜에 여러 개의 일정이 있을 경우 출력 오류

### ISSUE THREAD

**Issue by Yasasayi** [LeeJungHwan-Dev/JBNU_Slack_ChatBot#11]
**⚠️ 버그 설명** </br>
**동일한 날짜에 여러 개의 일정이 있을 경우 출력 오류.**

**⚙️ 버그 과정**
**버그가 발생한 과정을 아래에 작성해주세요.**
~~~
input: 학사일정 조회 - 9/1
expected output: 2학기 개강 & 2학기 수강신청 변경 기간
actual output: 2학기 수강신청 변경 기간
~~~

**🏞️ 스크린샷** </br>
![KakaoTalk_20221124_222804192](https://user-images.githubusercontent.com/113432477/203796060-01a0e469-e8c9-4cf8-bb0c-18cd926a68c7.png)

**데스크탑:**
 - OS: Windows 10
 - Browser: VS Code, Slack

**Comment by LeeJeongHwan-Dev** [comment]
# ✅ 해결 완료

**좋은 지적 감사합니다. 
날짜가 중복되는 학사 일정은 key 값을 하나 더 추가하여 출력하는 방법으로 해결했습니다.**

---

**⚠️ 버그 설명** </br>
**동일한 날짜에 여러 개의 일정이 있을 경우 출력 오류.**

**⚙️ 버그 과정**
**버그가 발생한 과정을 아래에 작성해주세요.**
~~~
input: 학사일정 조회 - 9/1
expected output: 2학기 개강 & 2학기 수강신청 변경 기간
actual output: 2학기 수강신청 변경 기간
~~~

**🏞️ 스크린샷** </br>
<img width="332" alt="스크린샷 2022-11-25 오전 2 24 38" src="https://user-images.githubusercontent.com/93726941/203839770-e5e7a663-063f-420f-91b5-103c296121d1.png">



**데스크탑:**
 - OS: MacOs
 - Browser: VS Code, Slack
