### ISSUE TITLE
특정 입력에 따른 Levenshtein distance 계산 오류

### ISSUE THREAD

**Issue by Yasasayi** [LeeJungHwan-Dev/JBNU_Slack_ChatBot#14]
**⚠️ 버그 설명** </br>
input에 !가 포함될 경우 Levenshtein distance를 의도한 대로 계산하지 못하는 오류

**⚙️ 버그 과정**
~~~
input - !!!!!!!!!!!!!!!!!!!!!Engineering!!!!!!!!!!!!!!!!!!!!!!!!!
expected - Something else that includes 'Engineering'
actual - Architectural Engineering -  College of Engineering Building 1, 132
         Accounting - College of Commerce 2, 9999
~~~

**🏞️ 스크린샷** </br>
![KakaoTalk_20221210_152849489](https://user-images.githubusercontent.com/113432477/206835839-e6e54898-5fd9-4d63-bb75-43e52a6ae11d.png)

**데스크탑:**
 - OS: Windows 10
 - Browser: VS Code, Slack

**Comment by LeeJeongHwan-Dev** [comment]
네 확인했습니다. 좋은 테스트케이스인 거 같네요.
맨 처음 제시해 주신 아이디어처럼 가중치를 더하는 방식으로 했을 때 학과명이 짧은 학과가 distance의 시작이 적어 결국 학과명이 긴 학과는 순서가 뒤로 밀렸습니다.

그래서 기존 "!" 로 보정하는 방식이 아닌 특수문자를 사용해 보정하여 사용자의 입력이 정말 특이한 케이스가 아닌 이상 전부 올바르게 출력되는 걸 확인했습니다.

즉, 학과명에 특수문자가 들어가지 않는 이상 잘 작동하는 코드라고 생각됩니다.

🏞️ 스크린샷

<img width="571" alt="무제" src="https://user-images.githubusercontent.com/93726941/206836328-d6fa784d-96dd-46d2-85c4-e1765ab80ba7.png">
