### ISSUE TITLE
Index.js 잘못된 모듈 불러오는 오류

### ISSUE THREAD

**Issue by Yasasayi** [LeeJungHwan-Dev/JBNU_Slack_ChatBot#18]
**⚠️ 버그 설명** </br>
sendAddress를 호출해야하는데 searchAddress를 호출해서 Feature #4가 동작하지 않는 오류

**⚙️ 버그 과정**
~~~
input: 학과 사무실 조회 - any input
output: X (error)
~~~

**🏞️ 스크린샷** </br>
![error](https://user-images.githubusercontent.com/113432477/206873817-7127159a-9e5e-4ce5-8c0f-a8fa0cb63b5e.PNG)

**데스크탑:**

 - OS: Windows 10
 - Browser: VS Code, Slack

**코멘트**
수정 시, 모듈 이름도 통일해주세요.

**Comment by LeeJeongHwan-Dev** [comment]
네 해당 부분 확인 및 해결 했습니다. 
* #19
